name: Main workflow

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - ocaml.5.1.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install npm packages
        if: runner.os == 'Linux'
        run: yarn install --immutable

      - name: Check formatting
        if: runner.os == 'Linux'
        run: yarn fmt:check

      - name: Check lint
        if: runner.os == 'Linux'
        run: yarn lint

      - name: Check type
        if: runner.os == 'Linux'
        run: yarn typecheck

      - name: Ensure dist directory is up-to-date
        if: runner.os == 'Linux'
        shell: bash
        run: |
          yarn build
          if [ "$(git status dist lint-doc lint-fmt lint-opam --porcelain | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ./
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
        if: runner.os == 'Linux'

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ./
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-repositories: |
            dra27: https://github.com/dra27/opam-repository.git#windows-5.0
            override: https://github.com/shym/custom-opam-repository.git#cyg
            default: https://github.com/fdopen/opam-repository-mingw.git#opam2
            upstream: https://github.com/ocaml/opam-repository.git
        if: runner.os == 'Windows'

      - run: opam depext uri --install
